[workspace]
resolver = "2"
members = [
    "fact",
    "fact-api",
    "fact-ebpf",
]
default-members = ["fact"]

[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = { version = "1", default-features = false, features = ["std", "backtrace"] }
aya = { git = "https://github.com/aya-rs/aya.git", rev = "c29cd71cb4fe1440bc0d566633afa822f1b41fc5", default-features = false }
libc = { version = "0.2.159", default-features = false }
prost = "0.14.0"
prost-types = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.40.0", default-features = false, features = [
    "fs",
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
tonic = { version = "0.14.0" }

[profile.release]
debug = "line-tables-only"
