FROM quay.io/centos/centos:stream9 AS builder

WORKDIR /app

COPY . .
RUN dnf install -y rust cargo && \
        cargo build --release

FROM quay.io/centos/centos:stream9-minimal

COPY --from=builder /app/target/release/self-deleter /usr/local/bin

ENTRYPOINT ["self-deleter"]
